// src/constants/services.ts

export const COACH_SERVICES = [
  {
    category: 'Fitness & Musculation',
    subcategories: [
      'Remise en forme générale',
      'Perte de poids',
      'Prise de masse musculaire',
      'Musculation & Force',
      'CrossFit',
      'Functional training',
      'HIIT',
      'Circuit training',
    ],
  },
  {
    category: 'Cardio & Endurance',
    subcategories: [
      'Course à pied',
      'Trail running',
      'Marathon',
      'Cyclisme',
      'Natation',
      'Triathlon',
      'Endurance cardiovasculaire',
      'Marche sportive',
    ],
  },
  {
    category: 'Sports de combat',
    subcategories: [
      'Boxe anglaise',
      'Boxe française',
      'Kickboxing',
      'MMA',
      'Judo',
      'Karaté',
      'Taekwondo',
      'Arts martiaux mixtes',
    ],
  },
  {
    category: 'Sports collectifs',
    subcategories: [
      'Football',
      'Basketball',
      'Volleyball',
      'Handball',
      'Rugby',
      'Hockey',
      'Tennis',
      'Badminton',
    ],
  },
  {
    category: 'Yoga & Méditation',
    subcategories: [
      'Hatha Yoga',
      'Vinyasa Yoga',
      'Ashtanga Yoga',
      'Yin Yoga',
      'Hot Yoga',
      'Yoga thérapeutique',
      'Méditation pleine conscience',
      'Pranayama',
    ],
  },
  {
    category: 'Pilates & Posture',
    subcategories: [
      'Pilates mat',
      'Pilates machine',
      'Correction posturale',
      'Renforcement du core',
      'Stabilité',
      'Méthode Feldenkrais',
    ],
  },
  {
    category: 'Bien-être & Relaxation',
    subcategories: [
      'Stretching',
      'Mobilité articulaire',
      'Sophrologie',
      'Relaxation',
      'Gestion du stress',
      'Techniques de respiration',
      'Mindfulness',
    ],
  },
  {
    category: 'Préparation physique',
    subcategories: [
      'Préparation physique générale',
      'Préparation physique spécifique',
      'Préparation athlétique',
      'Performance sportive',
      'Préparation mentale sportive',
      'Récupération sportive',
    ],
  },
  {
    category: 'Rééducation & Santé',
    subcategories: [
      'Réathlétisation',
      'Rééducation post-blessure',
      'Sport santé',
      'Activité physique adaptée',
      'Prévention des blessures',
      'Dos et articulations',
    ],
  },
  {
    category: 'Populations spécifiques',
    subcategories: [
      'Seniors',
      'Enfants & Adolescents',
      'Femmes enceintes',
      'Post-partum',
      'Personnes en situation de handicap',
      'Débutants',
    ],
  },
  {
    category: 'Activités aquatiques',
    subcategories: [
      'Natation technique',
      'Aquagym',
      'Aqua-fitness',
      'Nage en eau libre',
      'Perfectionnement natation',
      'Water-polo',
    ],
  },
  {
    category: 'Danse & Expression',
    subcategories: [
      'Danse fitness',
      'Zumba',
      'Strong by Zumba',
      'Danse contemporaine',
      'Expression corporelle',
      'Danse latine',
    ],
  },
  {
    category: 'Outdoor & Nature',
    subcategories: [
      'Randonnée',
      'Trekking',
      'Escalade',
      'VTT',
      'Sports de plage',
      'Bootcamp outdoor',
      'Canoë-kayak',
    ],
  },
  {
    category: 'Nutrition & Lifestyle',
    subcategories: [
      'Coaching nutritionnel',
      'Nutrition sportive',
      'Perte de poids nutritionnelle',
      'Prise de masse nutritionnelle',
      'Équilibre alimentaire',
      'Coaching de vie',
    ],
  },
  {
    category: 'Coaching mental',
    subcategories: [
      'Préparation mentale',
      'Confiance en soi',
      'Motivation',
      'Gestion de la performance',
      'Visualisation',
      'Développement personnel',
    ],
  },
]
