import { defineStore } from 'pinia'
import type { CoachProfile } from '@/types/coach'
import type { Lead } from '@/types/Lead'
import { useSubscriptionStore } from './subscription'

export const useUserStore = defineStore('user', {
  state: () => ({
    isLoggedIn: true, // Set to true for demo purposes
    coach: {
      id: '1',
      firstName: 'Marc',
      lastName: 'Dubois',
      city: 'Paris',
      country: 'France',
      email: 'marc.dubois@example.com',
      emailVerified: true,
      phoneNumber: '+33 6 12 34 56 78',
      phoneVerified: false,
      services: [
        'Remise en forme',
        'Perte de poids',
        'Renforcement musculaire',
        'Nutrition sportive',
        'Motivation',
      ],
      photoUrl: '',
      description:
        "Coach sportif passionné avec 8 ans d'expérience. Spécialisé dans la remise en forme et la préparation physique.",
      diplomas: [
        {
          id: '1',
          name: 'BPJEPS Activités Gymniques',
          photoUrl: '',
          status: 'approved',
          submittedAt: new Date('2024-01-15'),
          reviewedAt: new Date('2024-01-20'),
          reviewedBy: 'admin',
        },
        {
          id: '2',
          name: 'Certificat en Nutrition Sportive',
          photoUrl: '',
          status: 'pending',
          submittedAt: new Date('2024-12-01'),
        },
      ],
      website: 'https://marc-dubois-coach.fr',
      accountStatus: 'approved',
      createdAt: new Date('2024-01-10'),
      suspensionReason: 'En attente de validation du certificat en nutrition sportive',
    } as CoachProfile | null,
    leads: [
      {
        id: 'lead_001',
        clientId: 'client_001',
        clientName: 'Sophie Martin',
        clientEmail: 'sophie.martin@example.com',
        clientPhone: '+33 6 98 76 54 32',
        clientGender: 'femme',
        clientAgeGroup: '25-35',
        location: 'Paris 15e',
        meetingLocationPreference: 'domicile_client',
        services: ['Remise en forme', 'Perte de poids'],
        level: 'debutant',
        groupPreference: 'solo',
        desiredStart: new Date('2024-12-15'),
        availability: "Matin et fin d'après-midi en semaine",
        weeklyAvailability: [
          { day: 'lundi', morning: true, afternoon: true, evening: false },
          { day: 'mardi', morning: true, afternoon: true, evening: false },
          { day: 'mercredi', morning: true, afternoon: false, evening: false },
          { day: 'jeudi', morning: true, afternoon: true, evening: false },
          { day: 'vendredi', morning: true, afternoon: true, evening: false },
          { day: 'samedi', morning: false, afternoon: false, evening: false },
          { day: 'dimanche', morning: false, afternoon: false, evening: false },
        ],
        sessionsPerWeek: 2,
        budget: '80-120€/mois',
        languages: ['français'],
        extraInfo: 'Préfère les séances à domicile, a une salle de sport dans son immeuble',
        genderPreference: 'peu_importe',
        acquiredAt: new Date('2024-12-01'),
        acquisitionType: 'accepted',
        originalProposalId: 'prop_001',
        leadStatus: 'contacted',
        lastContactDate: new Date('2024-12-02'),
        nextFollowUpDate: new Date('2024-12-09'),
        notes: [
          'Première prise de contact positive, très motivée',
          'A des créneaux flexibles, recherche une approche progressive',
        ],
        contactAttempts: 2,
        responseReceived: true,
        meetingScheduled: true,
        contractSigned: false,
        priority: 'high',
        tags: ['motivation_elevee', 'nouveau_client', 'flexible'],
        createdAt: new Date('2024-12-01'),
        updatedAt: new Date('2024-12-02'),
      },
      {
        id: 'lead_002',
        clientId: 'client_002',
        clientName: 'Thomas Leroy',
        clientEmail: 'thomas.leroy@example.com',
        clientPhone: '+33 6 87 65 43 21',
        clientGender: 'homme',
        clientAgeGroup: '35-45',
        location: 'Boulogne-Billancourt',
        meetingLocationPreference: 'salle_sport',
        services: ['Renforcement musculaire', 'Nutrition sportive'],
        level: 'intermediaire',
        groupPreference: 'small_group',
        desiredStart: new Date('2024-12-20'),
        availability: 'Soirées et week-ends',
        weeklyAvailability: [
          { day: 'lundi', morning: false, afternoon: false, evening: true },
          { day: 'mardi', morning: false, afternoon: false, evening: true },
          { day: 'mercredi', morning: false, afternoon: false, evening: true },
          { day: 'jeudi', morning: false, afternoon: false, evening: true },
          { day: 'vendredi', morning: false, afternoon: false, evening: true },
          { day: 'samedi', morning: true, afternoon: true, evening: true },
          { day: 'dimanche', morning: true, afternoon: true, evening: true },
        ],
        sessionsPerWeek: 3,
        budget: '100-150€/mois',
        languages: ['français', 'anglais'],
        extraInfo: "Ancien sportif, reprend après une pause, préfère l'entraînement en groupe",
        genderPreference: 'homme',
        acquiredAt: new Date('2024-11-28'),
        acquisitionType: 'purchased',
        originalProposalId: 'prop_002',
        amountPaid: 15,
        leadStatus: 'new',
        notes: [],
        contactAttempts: 0,
        responseReceived: false,
        meetingScheduled: false,
        contractSigned: false,
        priority: 'medium',
        tags: ['ancien_sportif', 'groupe_prefere'],
        createdAt: new Date('2024-11-28'),
        updatedAt: new Date('2024-11-28'),
      },
      {
        id: 'lead_003',
        clientId: 'client_003',
        clientName: 'Marie Dubois',
        clientEmail: 'marie.dubois@example.com',
        clientPhone: '+33 6 76 54 32 10',
        clientGender: 'femme',
        clientAgeGroup: '45-55',
        location: 'Neuilly-sur-Seine',
        meetingLocationPreference: 'exterieur',
        services: ['Remise en forme', 'Motivation'],
        level: 'debutant',
        groupPreference: 'solo',
        desiredStart: new Date('2024-12-10'),
        availability: 'Matinées uniquement',
        weeklyAvailability: [
          { day: 'lundi', morning: true, afternoon: false, evening: false },
          { day: 'mardi', morning: true, afternoon: false, evening: false },
          { day: 'mercredi', morning: true, afternoon: false, evening: false },
          { day: 'jeudi', morning: true, afternoon: false, evening: false },
          { day: 'vendredi', morning: true, afternoon: false, evening: false },
          { day: 'samedi', morning: true, afternoon: false, evening: false },
          { day: 'dimanche', morning: false, afternoon: false, evening: false },
        ],
        sessionsPerWeek: 1,
        budget: '120-180€/mois',
        languages: ['français'],
        extraInfo: 'Recherche un accompagnement bienveillant, reprise après blessure',
        genderPreference: 'peu_importe',
        acquiredAt: new Date('2024-11-25'),
        acquisitionType: 'accepted',
        originalProposalId: 'prop_003',
        leadStatus: 'converted',
        lastContactDate: new Date('2024-11-30'),
        conversionValue: 480,
        conversionDate: new Date('2024-11-30'),
        notes: [
          'Excellente relation établie dès le premier contact',
          'Contrat signé pour 4 mois, très satisfaite des premiers résultats',
        ],
        contactAttempts: 3,
        responseReceived: true,
        meetingScheduled: true,
        contractSigned: true,
        clientRating: 5,
        coachFeedback: 'Cliente exemplaire, très investie et reconnaissante',
        priority: 'low',
        tags: ['client_converti', 'excellent_feedback'],
        createdAt: new Date('2024-11-25'),
        updatedAt: new Date('2024-11-30'),
      },
      {
        id: 'lead_004',
        clientId: 'client_004',
        clientName: 'David Chen',
        clientEmail: 'david.chen@example.com',
        clientPhone: '+33 6 65 43 21 09',
        clientGender: 'homme',
        clientAgeGroup: '25-35',
        location: 'Paris 11e',
        meetingLocationPreference: 'en_ligne',
        services: ['Perte de poids', 'Nutrition sportive'],
        level: 'avance',
        groupPreference: 'online',
        desiredStart: new Date('2024-12-08'),
        availability: 'Très flexible, préfère le soir',
        weeklyAvailability: [
          { day: 'lundi', morning: false, afternoon: true, evening: true },
          { day: 'mardi', morning: false, afternoon: true, evening: true },
          { day: 'mercredi', morning: false, afternoon: false, evening: true },
          { day: 'jeudi', morning: false, afternoon: true, evening: true },
          { day: 'vendredi', morning: false, afternoon: false, evening: true },
          { day: 'samedi', morning: true, afternoon: true, evening: true },
          { day: 'dimanche', morning: false, afternoon: true, evening: true },
        ],
        sessionsPerWeek: 4,
        budget: '60-100€/mois',
        languages: ['français', 'anglais', 'chinois'],
        extraInfo: 'Travaille beaucoup, cherche efficacité max avec coaching en ligne',
        genderPreference: 'peu_importe',
        acquiredAt: new Date('2024-11-20'),
        acquisitionType: 'purchased',
        originalProposalId: 'prop_004',
        amountPaid: 25,
        leadStatus: 'lost',
        lastContactDate: new Date('2024-11-22'),
        notes: [
          'Contact difficile, horaires très changeants',
          'A finalement choisi une solution moins chère en ligne',
        ],
        contactAttempts: 5,
        responseReceived: true,
        meetingScheduled: false,
        contractSigned: false,
        priority: 'low',
        tags: ['perdu', 'prix_sensible'],
        createdAt: new Date('2024-11-20'),
        updatedAt: new Date('2024-11-22'),
      },
      {
        id: 'lead_005',
        clientId: 'client_005',
        clientName: 'Amélie Robert',
        clientEmail: 'amelie.robert@example.com',
        clientPhone: '+33 6 54 32 10 98',
        clientGender: 'femme',
        clientAgeGroup: '18-25',
        location: 'Vincennes',
        meetingLocationPreference: 'flexible',
        services: ['Remise en forme', 'Motivation'],
        level: 'debutant',
        groupPreference: 'group',
        desiredStart: new Date('2024-12-12'),
        availability: 'Après-midi et soirées',
        weeklyAvailability: [
          { day: 'lundi', morning: false, afternoon: true, evening: true },
          { day: 'mardi', morning: false, afternoon: true, evening: true },
          { day: 'mercredi', morning: false, afternoon: true, evening: true },
          { day: 'jeudi', morning: false, afternoon: false, evening: true },
          { day: 'vendredi', morning: false, afternoon: true, evening: true },
          { day: 'samedi', morning: false, afternoon: true, evening: false },
          { day: 'dimanche', morning: false, afternoon: false, evening: false },
        ],
        sessionsPerWeek: 2,
        budget: '40-80€/mois',
        languages: ['français'],
        extraInfo: 'Étudiante, budget serré mais très motivée',
        genderPreference: 'femme',
        acquiredAt: new Date('2024-11-30'),
        acquisitionType: 'accepted',
        originalProposalId: 'prop_005',
        leadStatus: 'in_progress',
        lastContactDate: new Date('2024-12-03'),
        nextFollowUpDate: new Date('2024-12-10'),
        notes: [
          "Première séance d'essai prévue cette semaine",
          'Budget étudiant mais grande motivation',
        ],
        contactAttempts: 1,
        responseReceived: true,
        meetingScheduled: true,
        contractSigned: false,
        priority: 'medium',
        tags: ['etudiante', 'budget_serre', 'motivee'],
        createdAt: new Date('2024-11-30'),
        updatedAt: new Date('2024-12-03'),
      },
    ] as Lead[],
  }),
  actions: {
    login(data: CoachProfile) {
      this.isLoggedIn = true
      this.coach = data
    },
    logout() {
      this.isLoggedIn = false
      this.coach = null
    },

    // Subscription actions - delegate to subscription store
    toggleSubscription() {
      const subscriptionStore = useSubscriptionStore()
      subscriptionStore.toggleSubscription()
    },

    activateSubscription() {
      const subscriptionStore = useSubscriptionStore()
      subscriptionStore.subscribeToPlan('pro') // Default to pro plan
    },

    cancelSubscription() {
      const subscriptionStore = useSubscriptionStore()
      subscriptionStore.cancelSubscription()
    },

    upgradeSubscription() {
      const subscriptionStore = useSubscriptionStore()
      subscriptionStore.upgradeToPlan('premium')
    },
  },
})
