import { createClient } from '@supabase/supabase-js'

// Supabase configuration from environment variables
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY

if (!supabaseUrl || !supabaseAnonKey) {
  console.error('Missing Supabase configuration:', { supabaseUrl, hasAnonKey: !!supabaseAnonKey })
  throw new Error('Missing Supabase configuration. Please check your environment variables.')
}

// Create Supabase client with enhanced session management
export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce', // Use PKCE flow for better security
    storage: localStorage, // Explicitly use localStorage
    storageKey: 'coachiles-auth-token', // Custom storage key
    debug: import.meta.env.DEV, // Enable debug in development
  },
  realtime: {
    params: {
      eventsPerSecond: 2,
    },
  },
  global: {
    headers: {
      'X-Client-Info': 'coachiles-web-app',
    },
  },
})

// Database types (will be generated by Supabase CLI)
export interface Database {
  public: {
    Tables: {
      coaches: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          email: string
          first_name: string
          phone: string | null
          avatar_url: string | null
          bio: string | null
          specialties: string[]
          certifications: string[]
          experience_years: number
          hourly_rate: number
          availability: string[]
          locations: string[]
          languages: string[]
          is_active: boolean
          subscription_type: string
          subscription_expires_at: string | null
          rating: number
          total_sessions: number
          response_time_hours: number
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          email: string
          first_name: string
          phone?: string | null
          avatar_url?: string | null
          bio?: string | null
          specialties?: string[]
          certifications?: string[]
          experience_years?: number
          hourly_rate?: number
          availability?: string[]
          locations?: string[]
          languages?: string[]
          is_active?: boolean
          subscription_type?: string
          subscription_expires_at?: string | null
          rating?: number
          total_sessions?: number
          response_time_hours?: number
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          email?: string
          first_name?: string
          phone?: string | null
          avatar_url?: string | null
          bio?: string | null
          specialties?: string[]
          certifications?: string[]
          experience_years?: number
          hourly_rate?: number
          availability?: string[]
          locations?: string[]
          languages?: string[]
          is_active?: boolean
          subscription_type?: string
          subscription_expires_at?: string | null
          rating?: number
          total_sessions?: number
          response_time_hours?: number
        }
      }
      leads: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          client_name: string
          client_email: string
          client_phone: string
          preferred_coaching: string[]
          goals: string
          experience: string
          availability: string
          budget: string
          location: string
          additional_info: string | null
          status: string
          coach_id: string | null
          coach_note: string | null
          contacted_at: string | null
          converted_at: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          client_name: string
          client_email: string
          client_phone: string
          preferred_coaching: string[]
          goals: string
          experience: string
          availability: string
          budget: string
          location: string
          additional_info?: string | null
          status?: string
          coach_id?: string | null
          coach_note?: string | null
          contacted_at?: string | null
          converted_at?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          client_name?: string
          client_email?: string
          client_phone?: string
          preferred_coaching?: string[]
          goals?: string
          experience?: string
          availability?: string
          budget?: string
          location?: string
          additional_info?: string | null
          status?: string
          coach_id?: string | null
          coach_note?: string | null
          contacted_at?: string | null
          converted_at?: string | null
        }
      }
      subscriptions: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          coach_id: string
          plan_type: string
          status: string
          current_period_start: string
          current_period_end: string
          price: number
          features: string[]
          is_active: boolean
          auto_renew: boolean
          payment_method: string | null
          last_payment_at: string | null
          next_payment_at: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          coach_id: string
          plan_type: string
          status?: string
          current_period_start: string
          current_period_end: string
          price: number
          features?: string[]
          is_active?: boolean
          auto_renew?: boolean
          payment_method?: string | null
          last_payment_at?: string | null
          next_payment_at?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          coach_id?: string
          plan_type?: string
          status?: string
          current_period_start?: string
          current_period_end?: string
          price?: number
          features?: string[]
          is_active?: boolean
          auto_renew?: boolean
          payment_method?: string | null
          last_payment_at?: string | null
          next_payment_at?: string | null
        }
      }
      services: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          coach_id: string
          name: string
          description: string | null
          category: string
          subcategory: string | null
          price: number
          duration_minutes: number
          location_type: string
          group_size: string
          max_participants: number
          is_active: boolean
          requires_approval: boolean
          advance_booking_hours: number
          tags: string[]
          target_audience: string[]
          prerequisites: string | null
          materials_included: string | null
          cancellation_policy: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          coach_id: string
          name: string
          description?: string | null
          category: string
          subcategory?: string | null
          price: number
          duration_minutes: number
          location_type?: string
          group_size?: string
          max_participants?: number
          is_active?: boolean
          requires_approval?: boolean
          advance_booking_hours?: number
          tags?: string[]
          target_audience?: string[]
          prerequisites?: string | null
          materials_included?: string | null
          cancellation_policy?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          coach_id?: string
          name?: string
          description?: string | null
          category?: string
          subcategory?: string | null
          price?: number
          duration_minutes?: number
          location_type?: string
          group_size?: string
          max_participants?: number
          is_active?: boolean
          requires_approval?: boolean
          advance_booking_hours?: number
          tags?: string[]
          target_audience?: string[]
          prerequisites?: string | null
          materials_included?: string | null
          cancellation_policy?: string | null
        }
      }
      bookings: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          service_id: string
          coach_id: string
          client_name: string
          client_email: string
          client_phone: string | null
          scheduled_at: string
          duration_minutes: number
          timezone: string
          status: string
          payment_status: string
          total_amount: number
          currency: string
          notes: string | null
          internal_notes: string | null
          confirmed_at: string | null
          cancelled_at: string | null
          cancellation_reason: string | null
          reminder_sent_at: string | null
          meeting_url: string | null
          meeting_id: string | null
          meeting_password: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          service_id: string
          coach_id: string
          client_name: string
          client_email: string
          client_phone?: string | null
          scheduled_at: string
          duration_minutes: number
          timezone?: string
          status?: string
          payment_status?: string
          total_amount: number
          currency?: string
          notes?: string | null
          internal_notes?: string | null
          confirmed_at?: string | null
          cancelled_at?: string | null
          cancellation_reason?: string | null
          reminder_sent_at?: string | null
          meeting_url?: string | null
          meeting_id?: string | null
          meeting_password?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          service_id?: string
          coach_id?: string
          client_name?: string
          client_email?: string
          client_phone?: string | null
          scheduled_at?: string
          duration_minutes?: number
          timezone?: string
          status?: string
          payment_status?: string
          total_amount?: number
          currency?: string
          notes?: string | null
          internal_notes?: string | null
          confirmed_at?: string | null
          cancelled_at?: string | null
          cancellation_reason?: string | null
          reminder_sent_at?: string | null
          meeting_url?: string | null
          meeting_id?: string | null
          meeting_password?: string | null
        }
      }
      reviews: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          booking_id: string | null
          coach_id: string
          service_id: string | null
          client_name: string
          client_email: string
          rating: number
          title: string | null
          comment: string | null
          communication_rating: number | null
          professionalism_rating: number | null
          expertise_rating: number | null
          value_rating: number | null
          is_verified: boolean
          is_published: boolean
          is_anonymous: boolean
          moderation_status: string
          moderation_notes: string | null
          coach_response: string | null
          coach_responded_at: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          booking_id?: string | null
          coach_id: string
          service_id?: string | null
          client_name: string
          client_email: string
          rating: number
          title?: string | null
          comment?: string | null
          communication_rating?: number | null
          professionalism_rating?: number | null
          expertise_rating?: number | null
          value_rating?: number | null
          is_verified?: boolean
          is_published?: boolean
          is_anonymous?: boolean
          moderation_status?: string
          moderation_notes?: string | null
          coach_response?: string | null
          coach_responded_at?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          booking_id?: string | null
          coach_id?: string
          service_id?: string | null
          client_name?: string
          client_email?: string
          rating?: number
          title?: string | null
          comment?: string | null
          communication_rating?: number | null
          professionalism_rating?: number | null
          expertise_rating?: number | null
          value_rating?: number | null
          is_verified?: boolean
          is_published?: boolean
          is_anonymous?: boolean
          moderation_status?: string
          moderation_notes?: string | null
          coach_response?: string | null
          coach_responded_at?: string | null
        }
      }
      payments: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          booking_id: string | null
          coach_id: string
          amount: number
          currency: string
          payment_method: string | null
          transaction_id: string | null
          status: string
          payment_type: string
          platform_fee: number
          payment_processor_fee: number
          coach_earnings: number
          stripe_payment_intent_id: string | null
          stripe_charge_id: string | null
          paypal_transaction_id: string | null
          processed_at: string | null
          failed_at: string | null
          refunded_at: string | null
          description: string | null
          failure_reason: string | null
          metadata: Record<string, unknown>
          payout_id: string | null
          payout_status: string | null
          payout_date: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          booking_id?: string | null
          coach_id: string
          amount: number
          currency?: string
          payment_method?: string | null
          transaction_id?: string | null
          status?: string
          payment_type?: string
          platform_fee?: number
          payment_processor_fee?: number
          coach_earnings: number
          stripe_payment_intent_id?: string | null
          stripe_charge_id?: string | null
          paypal_transaction_id?: string | null
          processed_at?: string | null
          failed_at?: string | null
          refunded_at?: string | null
          description?: string | null
          failure_reason?: string | null
          metadata?: Record<string, unknown>
          payout_id?: string | null
          payout_status?: string | null
          payout_date?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          booking_id?: string | null
          coach_id?: string
          amount?: number
          currency?: string
          payment_method?: string | null
          transaction_id?: string | null
          status?: string
          payment_type?: string
          platform_fee?: number
          payment_processor_fee?: number
          coach_earnings?: number
          stripe_payment_intent_id?: string | null
          stripe_charge_id?: string | null
          paypal_transaction_id?: string | null
          processed_at?: string | null
          failed_at?: string | null
          refunded_at?: string | null
          description?: string | null
          failure_reason?: string | null
          metadata?: Record<string, unknown>
          payout_id?: string | null
          payout_status?: string | null
          payout_date?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']
export type InsertTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']
export type UpdateTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']
