import { createClient } from '@supabase/supabase-js'
import { config } from './config'

// Supabase configuration
const supabaseUrl = config.supabase.url
const supabaseAnonKey = config.supabase.anonKey

if (!supabaseUrl || !supabaseAnonKey) {
  console.error('Missing Supabase configuration:', { supabaseUrl, hasAnonKey: !!supabaseAnonKey })
  throw new Error('Missing Supabase configuration. Please check your environment variables.')
}

// Create Supabase client
export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  realtime: {
    params: {
      eventsPerSecond: 2,
    },
  },
})

// Test connection on load
supabase
  .from('coaches')
  .select('id, first_name, email')
  .limit(1)
  .then(({ data, error }) => {
    if (error) {
      console.error('❌ Supabase connection test failed:', error)
    } else {
      console.log('✅ Supabase connected successfully! Sample data:', data)
    }
  })

// Database types (will be generated by Supabase CLI)
export interface Database {
  public: {
    Tables: {
      coaches: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          email: string
          first_name: string
          phone: string | null
          avatar_url: string | null
          bio: string | null
          specialties: string[]
          certifications: string[]
          experience_years: number
          hourly_rate: number
          availability: string[]
          locations: string[]
          languages: string[]
          is_active: boolean
          subscription_type: string
          subscription_expires_at: string | null
          rating: number
          total_sessions: number
          response_time_hours: number
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          email: string
          first_name: string
          phone?: string | null
          avatar_url?: string | null
          bio?: string | null
          specialties?: string[]
          certifications?: string[]
          experience_years?: number
          hourly_rate?: number
          availability?: string[]
          locations?: string[]
          languages?: string[]
          is_active?: boolean
          subscription_type?: string
          subscription_expires_at?: string | null
          rating?: number
          total_sessions?: number
          response_time_hours?: number
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          email?: string
          first_name?: string
          phone?: string | null
          avatar_url?: string | null
          bio?: string | null
          specialties?: string[]
          certifications?: string[]
          experience_years?: number
          hourly_rate?: number
          availability?: string[]
          locations?: string[]
          languages?: string[]
          is_active?: boolean
          subscription_type?: string
          subscription_expires_at?: string | null
          rating?: number
          total_sessions?: number
          response_time_hours?: number
        }
      }
      leads: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          client_name: string
          client_email: string
          client_phone: string
          preferred_coaching: string[]
          goals: string
          experience: string
          availability: string
          budget: string
          location: string
          additional_info: string | null
          status: string
          coach_id: string | null
          coach_note: string | null
          contacted_at: string | null
          converted_at: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          client_name: string
          client_email: string
          client_phone: string
          preferred_coaching: string[]
          goals: string
          experience: string
          availability: string
          budget: string
          location: string
          additional_info?: string | null
          status?: string
          coach_id?: string | null
          coach_note?: string | null
          contacted_at?: string | null
          converted_at?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          client_name?: string
          client_email?: string
          client_phone?: string
          preferred_coaching?: string[]
          goals?: string
          experience?: string
          availability?: string
          budget?: string
          location?: string
          additional_info?: string | null
          status?: string
          coach_id?: string | null
          coach_note?: string | null
          contacted_at?: string | null
          converted_at?: string | null
        }
      }
      subscriptions: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          coach_id: string
          plan_type: string
          status: string
          current_period_start: string
          current_period_end: string
          price: number
          features: string[]
          is_active: boolean
          auto_renew: boolean
          payment_method: string | null
          last_payment_at: string | null
          next_payment_at: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          coach_id: string
          plan_type: string
          status?: string
          current_period_start: string
          current_period_end: string
          price: number
          features?: string[]
          is_active?: boolean
          auto_renew?: boolean
          payment_method?: string | null
          last_payment_at?: string | null
          next_payment_at?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          coach_id?: string
          plan_type?: string
          status?: string
          current_period_start?: string
          current_period_end?: string
          price?: number
          features?: string[]
          is_active?: boolean
          auto_renew?: boolean
          payment_method?: string | null
          last_payment_at?: string | null
          next_payment_at?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']
export type InsertTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']
export type UpdateTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']
